# Generated by Django 4.2.5 on 2023-09-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='You need to write a task', max_length=400)),
                ('create_date', models.DateTimeField(help_text='Date that the task was created', verbose_name='date created')),
                ('conclusion_date', models.DateTimeField(help_text='Optional value that the task should be concluded', verbose_name='date conclusion')),
            ],
        ),
    ]
