# Generated by Django 4.2.5 on 2023-09-30 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_task_concluded_alter_task_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='concluded',
            field=models.BooleanField(default=False, verbose_name='task concluded'),
        ),
        migrations.AlterField(
            model_name='task',
            name='conclusion_date',
            field=models.DateTimeField(help_text='Optional value that the task should be concluded', null=True, verbose_name='date conclusion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 17, 12, 23, 348360, tzinfo=datetime.timezone.utc), help_text='Date that the task was created', verbose_name='date created'),
        ),
    ]
